#version: '3.8'

services:
  # Next.js web application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ticketsystem?schema=public
      - NODE_ENV=production
    restart: always
    volumes:
      - ./.env:/app/.env
    networks:
      - app-network

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticketsystem
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
